### PR TITLE
Add method to access time since boot

### LINKED ISSUE #1509: Get vehicle time since boot
I'm writing mavsdk-based tests using `autopilot_tester` from the PX4 repo. The controls guy tests his stuff using MATLAB scripts that trigger certain inputs at certain times. My job is to replicate his tests in the integrated sitl environment. My first attempt was less than perfect because the sitl logs had a variable time scale. Next, I tried adjusting the time according to the speed-up factor. That kind of worked but still not great. Finally, I exposed `_last_time_boot_ms` via a `get_time()` method in the `info` interface, which lead to a usable solution.

Example MATLAB:
```
if simtime_sec >= 15.0
    OutputRC.RC_Thrust = 0.5;
end

if simtime_sec >= 20.0
    OutputRC.RC_Thrust = 0.6;
end

if simtime_sec >= 25.0
    OutputRC.RC_Thrust = 0.4;
end

if simtime_sec >= 30.0
    OutputRC.RC_Roll = 0.1;
end

if simtime_sec >= 35.0
    OutputRC.RC_Roll = -0.1;
end

if simtime_sec >= 40.0
    OutputRC.RC_Roll = 0.0;
    OutputRC.RC_Pitch = 0.1;
end

if simtime_sec >= 45.0
    OutputRC.RC_Pitch = -0.1;
end

if simtime_sec >= 50.0
    OutputRC.RC_Yaw = 0.2;
    OutputRC.RC_Pitch = 0.0;
end

if simtime_sec >= 55.0
    OutputRC.RC_Yaw = -0.2;
end

if simtime_sec >= 60.0
    OutputRC.RC_Yaw = 0.0;
end
```
C++ replica (`get_time()` is a local wrapper around a new `_info->get_time()` method I added):
```
	const auto start_time = get_time();
	do {
		CHECK(_manual_control->set_manual_control_input(0.0F, 0.0F, 0.5F, 0.0F)
		      == ManualControl::Result::Success);
		sleep_for(manual_control_update_period);
	} while (get_time() - start_time < seconds(20));

	do {
		CHECK(_manual_control->set_manual_control_input(0.0F, 0.0F, 0.6F, 0.0F)
		      == ManualControl::Result::Success);
		sleep_for(manual_control_update_period);
	} while (get_time() - start_time < seconds(25));

	do {
		CHECK(_manual_control->set_manual_control_input(0.0F, 0.0F, 0.4F, 0.0F)
		      == ManualControl::Result::Success);
		sleep_for(manual_control_update_period);
	} while (get_time() - start_time < seconds(30));

	do {
		CHECK(_manual_control->set_manual_control_input(0.0F, 0.1F, 0.4F, 0.0F)
		      == ManualControl::Result::Success);
		sleep_for(manual_control_update_period);
	} while (get_time() - start_time < seconds(35));

	do {
		CHECK(_manual_control->set_manual_control_input(0.0F, -0.1F, 0.4F, 0.0F)
		      == ManualControl::Result::Success);
		sleep_for(manual_control_update_period);
	} while (get_time() - start_time < seconds(40));

	do {
		CHECK(_manual_control->set_manual_control_input(-0.1F, 0.0F, 0.4F, 0.0F)
		      == ManualControl::Result::Success);
		sleep_for(manual_control_update_period);
	} while (get_time() - start_time < seconds(45));

	do {
		CHECK(_manual_control->set_manual_control_input(0.1F, 0.0F, 0.4F, 0.0F)
		      == ManualControl::Result::Success);
		sleep_for(manual_control_update_period);
	} while (get_time() - start_time < seconds(50));

	do {
		CHECK(_manual_control->set_manual_control_input(0.0F, 0.0F, 0.4F, 0.2F)
		      == ManualControl::Result::Success);
		sleep_for(manual_control_update_period);
	} while (get_time() - start_time < seconds(55));

	do {
		CHECK(_manual_control->set_manual_control_input(0.0F, 0.0F, 0.4F, -0.2F)
		      == ManualControl::Result::Success);
		sleep_for(manual_control_update_period);
	} while (get_time() - start_time < seconds(60));

	do {
		CHECK(_manual_control->set_manual_control_input(0.0F, 0.0F, 0.4F, 0.0F)
		      == ManualControl::Result::Success);
		sleep_for(manual_control_update_period);
	} while (get_time() - start_time < seconds(70));
```

### PR DESCRIPTION
**Pull request by danduril**
Closes #1509

### CODE REVIEW

**Comment by danduril** [comment]
Piggy-backing a method to start stabilized mode onto this PR.

**Comment by danduril** [comment]
The `get_time()` method returns a duration in the payload part of the pair<>. I considered making a conceptually cool `vehicle_clock` but it seemed overkill and too much extra functionality to test for my simple need.

**Comment by danduril** [comment]
Oops. I see that I edited a generated header. Will look into how to do this correctly and create new PR, later.

**Review by JonasVautherin — COMMENTED** [review]
Isn't [this](https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/info/info.proto#L56) what you want? :thinking:

**Comment by dgeorge83616** [comment]
Yes! I overlooked [this](https://github.com/mavlink/MAVSDK-Proto/blob/d5bcefa02233dc7f12aa4a9a5d40eaeef0dc4381/protos/info/info.proto#L13), and didn't yet understand the proto->generated code path. Thank you

**Pull request closed without merging**
