### PR TITLE
Add catalyst builds to CI

### PR DESCRIPTION
**Pull request by JonasVautherin**
I have no clue if that works :see_no_evil:

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Two notes:

1. It fails, I don't really know why and I don't have time to look into this. Open for contributions: if someone can fix that, I can probably continue the integration.
2. I also tried to build for M1, but it seems like it cannot be cross-compiled, so it will have to wait until github actions provide M1 machines.

**Comment by rligocki** [comment]
Based on this discussion (https://gitlab.kitware.com/cmake/cmake/-/issues/20132) I would suggest to change macOS SDK to iOS in catalyst build. 

In iOS configure, there is iOS SDK (Line 16 in configure part):
`-- Using SDK: /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk`
In catalyst build there is macOS SDK (Line 14 in configure part):
`-- Using SDK:  /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk`

**Comment by rligocki** [comment]
In configure part of build on line 104 there is another clue. This could be proof of my previous idea and future collision. 
`-- Using minimum deployment version: 13.0 (SDK version: 11.1)`

**Comment by julianoes** [comment]
@rligocki feel free to create a PR. If you happen to have an m1 to test that would be great.

**Pull request closed without merging**
