### PR TITLE
Update gtest

### PR DESCRIPTION
**Pull request by JonasVautherin**
It's been a while...

### CODE REVIEW

**Comment by julianoes** [comment]
I'm updating it to the latest release instead of main, let's see if that changes anything.

**Comment by julianoes** [comment]
Rebased and force pushed, hopefully this is fixed with updated proto (in the offboard PR).

**Comment by julianoes** [comment]
Nope :disappointed:

**Comment by JonasVautherin** [comment]
I don't get it. Did we merge changes without updating the proto submodule in `main`? But then all PRs should fail, right?

**Comment by julianoes** [comment]
That's right. I don't understand it.

**Pull request merged**
