### PR TITLE
follow_me: send velocity array

### PR DESCRIPTION
**Pull request by potaito**
The velocity fields of the follow-me mavlink message is currently hard-coded to `NAN`. With this PR mavsdk will send the actual values instead.

@julianoes sorry it took me so long.

### CODE REVIEW

**Review by JonasVautherin — CHANGES_REQUESTED** [review]
I think it's failing the style check. Can you run the following script?

```
./tools/fix_style.sh .
```

**Review by JonasVautherin — APPROVED** [review]
Looks good to me :+1:

Out of curiosity: could it be that we someday decide to use the others, too? E.g. `accel`, `attitude`, `rates`? Or is there a reason for never using them?

**Review by julianoes — COMMENTED** [review]
Awesome, thanks @potaito :potato:

**Comment by potaito** [comment]
> Looks good to me +1
> 
> Out of curiosity: could it be that we someday decide to use the others, too? E.g. `accel`, `attitude`, `rates`? Or is there a reason for never using them?

I suppose so, yes. But it wasn't part of my tests, so I did not include it :sweat_smile:

**Pull request merged**
