### PR TITLE
added set_position_velocity_acceleration_ned offboard function

### PR DESCRIPTION
**Pull request by alireza787b**
hello 
I just closed the last old pull request for this modification.
link:
https://github.com/mavlink/MAVSDK/pull/2049

it seems my branch was back from the main and I am not a git expert and couldn't rebase it.
i created a new branch and did the same steps just like last time on the updated main

everything works except I cannot build the mavsdk
I try to build the mavsdk_server using below command
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_MAVSDK_SERVER=ON -Bbuild/default -H.
cmake --build build/default -j8

but I get the following error  when building
In file included from /home/alireza/MAVSDK/src/mavsdk/plugins/param/param.cpp:7:
/home/alireza/MAVSDK/src/mavsdk/plugins/param/param_impl.h:37:58: error: ‘mavsdk::Param::ProtocolVersion’ has not been declared
   37 |     Param::Result select_component(int32_t component_id, Param::ProtocolVersion protocol_version);
      |                                                          ^~~~~
/home/alireza/MAVSDK/src/mavsdk/plugins/param/param_impl.h:44:12: error: ‘ProtocolVersion’ in ‘class mavsdk::Param’ does not name a type
   44 |     Param::ProtocolVersion _protocol_version{Param::ProtocolVersion::V1};
      |            ^~~~~~~~~~~~~~~
gmake[2]: *** [src/mavsdk/CMakeFiles/mavsdk.dir/build.make:1336: src/mavsdk/CMakeFiles/mavsdk.dir/plugins/param/param.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:983: src/mavsdk/CMakeFiles/mavsdk.dir/all] Error 2

I haven't edited anything related to param 

and when I try to run the fix styling I get this message:
clang-format not found
--> check: https://mavsdk.mavlink.io/main/en/cpp/guide/code_style.html#formatting-and-white-space

### CODE REVIEW

**Comment by JonasVautherin** [comment]
> clang-format not found

Did you try installing clang-format? :innocent: 

I fixed the style (@julianoes we should remember to squash the commits before merging)

**Comment by alireza787b** [comment]
thanks I instllaed clang and I now I can do that. I also pulled the latest commit you did.
but I didn't understand what exactly I need to do. when I try to build I get this following error in ubuntu
[ 24%] Building CXX object src/mavsdk/CMakeFiles/mavsdk.dir/plugins/param/param.cpp.o
In file included from /home/alireza/MAVSDK/src/mavsdk/plugins/param/param.cpp:7:
/home/alireza/MAVSDK/src/mavsdk/plugins/param/param_impl.h:37:58: error: ‘mavsdk::Param::ProtocolVersion’ has not been declared
   37 |     Param::Result select_component(int32_t component_id, Param::ProtocolVersion protocol_version);
      |                                                          ^~~~~
/home/alireza/MAVSDK/src/mavsdk/plugins/param/param_impl.h:44:12: error: ‘ProtocolVersion’ in ‘class mavsdk::Param’ does not name a type
   44 |     Param::ProtocolVersion _protocol_version{Param::ProtocolVersion::V1};
      |            ^~~~~~~~~~~~~~~
make[2]: *** [src/mavsdk/CMakeFiles/mavsdk.dir/build.make:1336: src/mavsdk/CMakeFiles/mavsdk.dir/plugins/param/param.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:983: src/mavsdk/CMakeFiles/mavsdk.dir/all] Error 2

**Comment by julianoes** [comment]
You don't need clang-format, you can just use the docker command instead that it suggests to use.

https://mavsdk.mavlink.io/main/en/cpp/guide/code_style.html#use-clang-format-in-docker

**Comment by julianoes** [comment]
I assume the problem is that the proto submodule needed rebasing, force pushing, and then this re-generating, fixing the style, and force pushing, yet again. I've done that. Let's check CI and then I'll merge proto, and afterwards this.

Thanks @alireza787b!

**Comment by julianoes** [comment]
Sorry closed by mistake.

**Review by julianoes — APPROVED** [review]

**Comment by julianoes** [comment]
Not waiting for CI, I expect this to go through now like before just with proto updated.

**Pull request merged**
