### PR TITLE
proto: forgot to update

### PR DESCRIPTION
**Pull request by julianoes**

### CODE REVIEW

**Comment by julianoes** [comment]
Oh dear, this already contains the arm authorizer stuff now.

**Comment by JonasVautherin** [comment]
I wanted to move everything into one repo, and I think it would work with MAVSDK-Java and MAVSDK-Python, but not MAVSDK-Swift. The reason was this: https://forums.swift.org/t/allow-package-swift-to-not-be-at-the-root-of-the-repository/60431

Still, it would work to have everything but MAVSDK-Swift in this repo. And MAVSDK-Swift/third party repos would just have to make a copy of the proto files (instead of using the git submodule). That would probably work :+1:.

**Comment by julianoes** [comment]
Ah, interesting. I forgot about that.

**Comment by julianoes** [comment]
Actually, we could probably just have a shim repo for Swift, and then pull in all files required and then publish whatever needs to be published, right?

**Comment by JonasVautherin** [comment]
Yes, that should work :+1:

**Pull request closed without merging**
