### PR TITLE
Add all MAVLink STATUSTEXT severity enum values to StatusTextType

### LINKED ISSUE #1025: Cover remaining statustext levels
Currently we don't support all statustext levels but we should.

https://github.com/mavlink/MAVSDK/blob/592238ce3d282d89fdff9ef47c4e95c29723f721/src/plugins/telemetry/include/plugins/telemetry/telemetry.h#L225-L227

### PR DESCRIPTION
**Pull request by coderkalyan**
Closes #1025.

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Now that it is auto-generated, it should be done [here](https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/telemetry/telemetry.proto#L488-L492) :wink:

**Comment by coderkalyan** [comment]
@JonasVautherin sorry this completely slipped my mind, but here you go: https://github.com/mavlink/MAVSDK-Proto/pull/174. Once that's merged, I can update the implementation here if needed.

**Comment by JonasVautherin** [comment]
That's merged :wink:

**Comment by coderkalyan** [comment]
@JonasVautherin just updated the telemetry_impl here. There was a bit of "collateral damage," since I just rebased the proto submodule to master (there was a commit in offboard.proto as well) and also generate_from_protos.sh changed a bit of formatting in the telemetry plugin directory. If you'd rather not have these in the merge, I'm happy to go cherry pick more carefully :smiley:

**Review by JonasVautherin — CHANGES_REQUESTED** [review]
You need to fix the style, by running `./tools/fix_style.sh .` :+1:

**Comment by coderkalyan** [comment]
@JonasVautherin oh, that's what I was missing! Should be good now, I think :wink:

**Comment by JonasVautherin** [comment]
The example failing is because we updated MAVLink, so you can ignore that. However, the "proto check" is failing. Are you sure you committed all the changes coming from `generate_from_protos.sh`? :thinking:

**Comment by coderkalyan** [comment]
@JonasVautherin I forgot to commit the changes to the offboard API, which isn't part of this PR but changed when I updated the proto submodule :smile: Fingers crossed it works this time!

**Review by JonasVautherin — APPROVED** [review]
Thanks a lot!

**Pull request merged**
