### PR TITLE
Split Ftp plugin into Ftp and FtpServer

### PR DESCRIPTION
**Pull request by julianoes**
The FTP plugin is a weird combination of client and server in one. Now that we have Components additional to Systems we can split it into client and server.

This includes:
- Complete refactor (almost rewrite) of server and client
- Slight API changes
- Using std::filesystem as much as possible everywhere
- Adding system tests

Depended on https://github.com/mavlink/MAVSDK-Proto/pull/319.

### CODE REVIEW

**Review by JonasVautherin — COMMENTED** [review]
Nitpick: the CI/Fedora stuff could have been done in another PR, this one is already big enough :see_no_evil:

**Comment by julianoes** [comment]
Oh, right. I was going to pull these commits out when I clean it up.

**Comment by julianoes** [comment]
I'm still hunting a crash in CI that I can't replicate...

**Comment by julianoes** [comment]
This PR is currently based on top of #2155.

**Review by JonasVautherin — APPROVED** [review]
That was a big effort! Congrats :blush:

**Pull request merged**
