### PR TITLE
Add Ubuntu 22.04 to CI

### PR DESCRIPTION
**Pull request by JonasVautherin**
@potaito: FYI

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Here, curl finds openssl on the system (which we don't expect for the superbuild):

```
2022-06-08T22:17:01.1231890Z -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.2")  
```

**Comment by julianoes** [comment]
> but that does not tell me why @julianoes changes in https://github.com/mavlink/MAVSDK/pull/1797 work thinking.

My changes don't work.

**Comment by JonasVautherin** [comment]
@julianoes @potaito: I think that was it :blush:

**Review by julianoes — APPROVED** [review]
Nice catch!

**Comment by potaito** [comment]
Thanks for the digging @JonasVautherin, I appreciate it!!

**Pull request merged**
