### PR TITLE
Fix style check in CI

### LINKED ISSUE #1008: Style check not working
The style check in CI is currently broken:
```
YAML:9:44: error: unknown key 'AllowAllConstructorInitializersOnNextLine'
AllowAllConstructorInitializersOnNextLine: false
                                           ^~~~~
Error reading /__w/MAVSDK/MAVSDK/.clang-format: Invalid argument
YAML:9:44: error: unknown key 'AllowAllConstructorInitializersOnNextLine'
AllowAllConstructorInitializersOnNextLine: false
                                           ^~~~~
```

### PR DESCRIPTION
**Pull request by julianoes**
This changes everything to clang-format-9.

Fixes #1008.

### CODE REVIEW

**Comment by julianoes** [comment]
:(
```
2020-03-06T11:46:30.1753978Z [34m[11:46:30|Info ] [0mHIGHRES_IMU.temperature [1] (98)11.8327 degrees C (mavlink_passthrough.cpp:61)
2020-03-06T11:46:30.1760844Z [34m[11:46:30|Info ] [0mHIGHRES_IMU.temperature [1] (99)11.8327 degrees C (mavlink_passthrough.cpp:61)
2020-03-06T11:46:30.1800451Z [0m[1;33m[0mterminate called after throwing an instance of 'std::system_error'
2020-03-06T11:46:30.1808449Z   what():  Resource deadlock avoided
2020-03-06T11:46:30.3568574Z Aborted (core dumped)
2020-03-06T11:46:31.2029814Z /home/user/Firmware/Tools/sitl_run.sh: line 132: 15634 Terminated              "/home/user/Firmware/build/px4_sitl_default/bin/px4" -d "/home/user/Firmware"/ROMFS/px4fmu_common -s etc/init.d-posix/rcS -t "/home/user/Firmware"/test_data
2020-03-06T11:46:31.2058801Z gzviewer: no process found
2020-03-06T11:46:31.2158299Z ##[error]Process completed with exit code 134.
```

**Comment by JonasVautherin** [comment]
> gzviewer: no process found. 

Does the crash come from that? Why is it different with 1.10?

**Comment by julianoes** [comment]
I think it's just a fluke. I'll try to reproduce it locally though to get a stacktrace.

**Comment by julianoes** [comment]
Ignoring the unrelated CI fail and merging this.

**Pull request merged**
