### PR TITLE
[WIP] Added basic orbit plugin structure

### PR DESCRIPTION
**Pull request by julianoes**
Just found this branch rotting, so I'm making a pull request out of it to keep it around.

### CODE REVIEW

**Comment by julianoes** [comment]
@MaEtUgR is this something we could/should add?

**Comment by MaEtUgR** [comment]
Yes, totally. Sorry it's still on my list.
Functionality should include sending this command (as `COMMAND_INT)` to start an orbit: https://mavlink.io/en/messages/common.html#MAV_CMD_DO_ORBIT
And evaluating this telemetry message: https://mavlink.io/en/messages/common.html#ORBIT_EXECUTION_STATUS to check for any updates.
I saw and still see it as an opportunity to learn properly adding something to the SDK but it was always post-poned. If you need it urgent feel free to fill the messages and ask me if there's something unclear.

**Comment by julianoes** [comment]
No, I'm fine to complete it. I just want to clean up the PRs.

**Comment by hamishwillee** [comment]
FYI, docs on Orbit are going into user guide in https://github.com/PX4/px4_user_guide/pull/472

**Comment by julianoes** [comment]
After the auto-generation will have a command too bootstrap a new plugin which makes this PR obsolete.

**Pull request closed without merging**
