### PR TITLE
Add set_actuator

### PR DESCRIPTION
**Pull request by coderkalyan**
Adds support for the MAV_CMD_DO_SET_ACTUATOR mavlink command.

Related proto: https://github.com/mavlink/MAVSDK-Proto/pull/172

### CODE REVIEW

**Comment by julianoes** [comment]
I think this depends on https://github.com/mavlink/MAVSDK-Proto/pull/172 and https://github.com/PX4/Firmware/pull/15281.

**Comment by julianoes** [comment]
@coderkalyan do you mind making another attempt at https://github.com/PX4/PX4-Autopilot/pull/15281 so that we could continue this here?

**Review by julianoes — DISMISSED** [review]

**Review by JonasVautherin — APPROVED** [review]
Thanks!

**Comment by mrpollo** [comment]
Just for reference the PR that brought this to PX4 is https://github.com/PX4/PX4-Autopilot/pull/16758

**Pull request merged**
