### PR TITLE
Changed map to unordered_map

### PR DESCRIPTION
**Pull request by roangel**
Fixes https://github.com/mavlink/MAVSDK/issues/1103

### CODE REVIEW

**Comment by roangel** [comment]
fixed style

**Comment by roangel** [comment]
CI fails:
image

**Comment by julianoes** [comment]
@roangel interesting, I wonder if that's related or not.

**Comment by julianoes** [comment]
@roangel ok it looks unrelated and like a bug with the mission item count.

**Comment by roangel** [comment]
Maybe it's this part?
image

**Comment by julianoes** [comment]
@roangel I was just fixing the asan issue (due to threading) in the integration test but haven't looked for the thing producing the wrong number of mission items. I think you found it, thanks!

**Comment by julianoes** [comment]
I think there might be a few more places even. And while looking at it I also stumbled across #1031.

**Comment by julianoes** [comment]
Thanks @roangel. I'll follow up with the mission part in another PR.

**Pull request merged**
