### PR TITLE
[RELEASE v1.4] Backport disable -ffast-math for iOS

### PR DESCRIPTION
**Pull request by ThomasDebrunner**
Backport of https://github.com/mavlink/MAVSDK/pull/2176

CI seems to fail, since macOS runners come with Python 3.12, which break the mavlink generators

### CODE REVIEW

**Review by JonasVautherin — CHANGES_REQUESTED** [review]
Same request as in the `main` PR: I think that the toolchain should be updated from upstream instead of patched, when possible.

**Comment by julianoes** [comment]
@JonasVautherin for v1.4 I would be ok just patching the one option. If we update the full toolchain here, we introduce more risk and churn.

**Comment by JonasVautherin** [comment]
@julianoes: good point, fine for me then :+1:

**Comment by julianoes** [comment]
Rebased and force-pushed.

**Review by julianoes — APPROVED** [review]

**Review by JonasVautherin — APPROVED** [review]

**Pull request merged**
