### PR TITLE
Added Orbit Command.

### PR DESCRIPTION
**Pull request by DoppleGangster**

### CODE REVIEW

**Review by JonasVautherin — CHANGES_REQUESTED** [review]
Looks good! You'll have to fix the style, though, by running the corresponding script:

```
./tools/fix_style.sh .
```

**Comment by DoppleGangster** [comment]
Style Updated. Thanks!

**Comment by DoppleGangster** [comment]
Is the docs failure something that should have been fixed with the fix_style.sh?

**Comment by JonasVautherin** [comment]
Oh, we're missing some more documentation in `action.proto` :see_no_evil:, but I think that's the last missing piece.

[The enum here](https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/action/action.proto#L188-L194) should be documented (similar to e.g. [this one](https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/camera/camera.proto#L218-L222)).

Would you mind opening a PR to MAVSDK-Proto with that change? I think after that we will be fine here, too :innocent:

**Comment by DoppleGangster** [comment]
👍 Sure not a problem.

**Comment by DoppleGangster** [comment]
I believe it should be good to go now.

**Review by JonasVautherin — APPROVED** [review]
Nice! Thanks a lot!

I just re-ran the CI because SITL failed on 1.11, but it seems fine otherwise :tada:

**Comment by DoppleGangster** [comment]
No problem! Thanks for helping me along the way!

**Pull request merged**
