### PR TITLE
Fix CI permissions when generating xcframework

### PR DESCRIPTION
**Pull request by julianoes**
Second try.

### CODE REVIEW

**Comment by julianoes** [comment]
Doesn't work, it's a known issue: https://github.com/actions/upload-artifact/issues/38.

**Comment by julianoes** [comment]
A workaround would be to upload the .zip in a .tar. Would that work @byuarus?

**Comment by JonasVautherin** [comment]
> Doesn't work, it's a known issue: [actions/upload-artifact#38](https://github.com/actions/upload-artifact/issues/38).

aha! Good catch

**Comment by julianoes** [comment]
Actually, given we use `actions/upload-release-asset@v1` for the upload as part of a release, this fix might still work, just not for the PR artifacts. So I'm going to try to merge this and make a release to test it.

**Pull request merged**
