### PR TITLE
added functionality to download geofences and rallypoints

### PR DESCRIPTION
**Pull request by mattes-bru**
mainly a copy & paste of download_mission for rallypoints  and geofence. Which solves my issue #2403

### CODE REVIEW

**Review by julianoes — COMMENTED** [review]
Hm, looks ok but did you do the proto file first and then generate the non-impl files?
https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/geofence/geofence.proto

https://mavsdk.mavlink.io/main/en/cpp/contributing/plugins.html#add-api-to-proto

**Comment by mattes-bru** [comment]
I have completely forgotten the protobuf part.  

Now I updated the proto files but when I generate the code as mentioned in the link the code style changes and so there are many updates, I don't want to commit. I also ran the fix-style.sh script but this did not help.

**Comment by julianoes** [comment]
I think this looks all fine. It's just complaining about one style problem. I'll try to run the script again.

**Comment by julianoes** [comment]
I'll squash and merge this as soon as CI is green.

**Comment by mattes-bru** [comment]
@julianoes is it possible to get this into a v2 release?

**Comment by julianoes** [comment]
I'd rather not have to deal with a v2 proto branch if possible.

**Pull request merged**
