### PR TITLE
#1207 added additional fields to FixedwingMetrics and  process_fixedwing_metrics

### PR DESCRIPTION
**Pull request by haydockjp**
#1207 added additional fields to FixedwingMetrics and  process_fixedwing_metrics

### CODE REVIEW

**Review by julianoes — CHANGES_REQUESTED** [review]
Note, the interface is auto-generated. This means the change needs to happen in https://github.com/mavlink/MAVSDK-Proto/blob/1ee7a19995053b840c58f4421271ea8eefbe8688/protos/telemetry/telemetry.proto#L599-L604 first.

**Comment by haydockjp** [comment]
Ah. I'll see about updating that too

**Comment by haydockjp** [comment]
I've updated the Proto definition: https://github.com/mavlink/MAVSDK-Proto/pull/176

**Comment by haydockjp** [comment]
I've re-done the prototype PR. And I updated the code for the SDK, to include that name change and the type change.

**Comment by julianoes** [comment]
There was no follow-up here in a while, so I closed https://github.com/mavlink/MAVSDK-Proto/pull/182 and will close this PR as well. @haydockjp if you want to pick this back up, please re-open the PR and I'm happy to discuss it again.

**Pull request closed without merging**
