### PR TITLE
fix telemetry docs

### PR DESCRIPTION
**Pull request by hamishwillee**
This fixes broken docs.

@julianoes @JonasVautherin Historically broken docs stopped commits merging. Can we re-enable that? This took a while to identify.

### CODE REVIEW

**Comment by JonasVautherin** [comment]
> Historically broken docs stopped commits merging.

@julianoes: oh was that done by Jenkins?

**Comment by julianoes** [comment]
@JonasVautherin could be. Sounds like we need to add it again!

**Comment by hamishwillee** [comment]
Yes please!

**Comment by julianoes** [comment]
@hamishwillee #979.

**Pull request merged**
