### PR TITLE
fixed log_files proto

### PR DESCRIPTION
**Pull request by dayjaby**
Follow-up on https://github.com/mavlink/MAVSDK-Proto/pull/304

### CODE REVIEW

**Review by julianoes — COMMENTED** [review]
Hm, now this breaks the API, so we can't release it for v1.4 but it would go into v2.

Is there nothing we can do to fix this in a way not to break the API? :thinking:

**Review by JonasVautherin — APPROVED** [review]

**Comment by dayjaby** [comment]
> Is there nothing we can do to fix this in a way not to break the API? thinking

We could change the way how the API gets generated for Python/Java/... if there is a sync and async function with the same name, only expose the async one - or expose the sync one with a different name.

**Comment by JonasVautherin** [comment]
> We could change the way how the API gets generated for Python/Java/... if there is a sync and async function with the same name, only expose the async one - or expose the sync one with a different name.

That seems overkill to if that's just for v1.4...

**Comment by julianoes** [comment]
@JonasVautherin  had the idea of only using that fix for Python and Java, but not change for C++ here.

I create a branch with the commit: https://github.com/mavlink/MAVSDK-Proto/tree/v1.4-log-files-fix

**Comment by julianoes** [comment]
> @JonasVautherin had the idea of only using that fix for Python and Java, but not change for C++ here.

Nevermind, this only goes into v2.0, so that's fine, merging.

**Pull request merged**
