### PR TITLE
cmake: install mavlink headers in correct dir

### PR DESCRIPTION
**Pull request by JonasVautherin**
Taken from https://github.com/mavlink/MAVSDK/commit/0c8e2367952b3233669739d439a13f2ccb568470, as it feels useful to merge it ASAP.

### CODE REVIEW

**Comment by Katawann** [comment]
I work with a deb package build locally on my side it's all good, but if others try to work with the deb provided on github it won't work

**Comment by Katawann** [comment]
@julianoes Would it be possible to do a patch release ? Or do you have a plan to integrate this correction in v1.5.0 and when could we except to be released ?

**Comment by julianoes** [comment]
Thanks for the note @Katawann. Here comes a patch for v1.4: #1911.

**Comment by julianoes** [comment]
I have the feeling this probably is not required for v1.4. It seems to be broken in v1.4.7. I'll revert it.

The changes in `main` will eventually be released as v2.

**Comment by Katawann** [comment]
Arf too bad. I'll wait for new release to test the installation then. Thank you for your help anyway !

**Comment by JonasVautherin** [comment]
But it works in `main`, doesn't it?

**Comment by Katawann** [comment]
I need to test again because I need to build the package to include it in my docker. I come back to you when I found some time to test it

**Comment by JonasVautherin** [comment]
Got it! Let us know if you find a patch, would be helpful :blush:

**Comment by Katawann** [comment]
I just build debian package with `main` branch but it still fail with the same error:
```
/usr/include/mavsdk/plugins/mavlink_passthrough/mavlink_include.h:3:10: fatal error: mavlink/v2.0/common/mavlink.h: No such file or directory
#include "mavlink/v2.0/common/mavlink.h"
```

Now let's found a fix which does not break installation for others...

**Comment by julianoes** [comment]
Ok, so takeaway: main is broken, release should (again be fine) as it was.

**Pull request merged**
