### PR TITLE
Try apple M1 for fun

### PR DESCRIPTION
**Pull request by JonasVautherin**
Not sure I understand how to use https://github.com/github/roadmap/issues/507, but just wanted to run something, out of curiosity :innocent:

### CODE REVIEW

**Comment by julianoes** [comment]
Not sure if I'd call this fun :joy:.

**Comment by julianoes** [comment]
Apparently it's ready, let's try it again!

**Comment by julianoes** [comment]
Nevermind, this is only ready for self hosted runners.

**Comment by JonasVautherin** [comment]
Well, maybe later.

**Pull request closed without merging**
