### PR TITLE
Rename example into examples

### PR DESCRIPTION
**Pull request by shrit**
Signed-off-by: Omar Shrit <shrit@lri.fr>

### CODE REVIEW

**Comment by hamishwillee** [comment]
I put it in the "more correct but not worth the effort" basket. However since most of the effort has been done sure.
@shrit Can you in parallel update all the documentation that references this? https://mavsdk.mavlink.io/develop/en/index.html

**Comment by julianoes** [comment]
Thanks @shrit, and the test failure looks unrelated.

**Comment by julianoes** [comment]
Merging as soon as docs are in sync.

**Comment by shrit** [comment]
@hamishwillee, Agreed, However, the doc are done in mavsdk-doc repository?

**Comment by julianoes** [comment]
@shrit https://github.com/mavlink/MAVSDK-docs/

**Pull request merged**
