### PR TITLE
Use landed state to improve taking off

### PR DESCRIPTION
**Pull request by shrit**
This pull request is made to allow easier debug to the problem described in the issue https://github.com/mavlink/MAVSDK/issues/885 
Please do not merge this pull request.
It might require several taking off with landed state to see the problem (block into infinite while loop)
On the other hand, flight mode will never block in the while loop.

Even if you receive landed state or flight mode asynchronously it will be the same problem

To use the landed sate:
`./offboard udp://:14540 landed_state `

To use the flight mode
`./offboard udp://:14540 flight_mode`

### CODE REVIEW

**Comment by shrit** [comment]
Ok, Would you like to keep both of them? the landed state and the flight mode as a use case for the users?

**Comment by julianoes** [comment]
Oh I'm stupid, this was only to debug! Sorry!

**Comment by shrit** [comment]
@julianoes, However, we can replace the sleep by using the flight mode to wait for the takeoff process to be completed.
What do you think of the last commit, I think this can be merged

**Comment by julianoes** [comment]
But this is then just a workaround for the fact that PX4 is not picking up the landed state correctly. However, that will be fixed with https://github.com/PX4/Firmware/pull/13075/commits/f913cc24aec47fab3c55aad35841d41e30a4199d.

**Comment by shrit** [comment]
Ok, So I will replace it with the flight mode with landed state, then you can merge when it is fixed at PX4 level.

**Pull request closed without merging**
