### PR TITLE
add arm64-lts docker workflow

### PR DESCRIPTION
**Pull request by AlexKlimaj**
This is an attempt to add an arm64-lts target which is needed on Jetson Jetpack 5.

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Let's see what the CI says :blush:

**Comment by julianoes** [comment]
I usually run this docker script manually and do the push, so that would explain the failure here.

**Comment by julianoes** [comment]
Built and pushed. Now I'm re-running the failed jobs.

@AlexKlimaj have you thought about the naming of the LTS one? Should it be called debian 11 or something instead? We'll have to see what happens I suppose.

**Comment by AlexKlimaj** [comment]
Hm I don't know what the best name for it should be.

**Comment by julianoes** [comment]
It looks like right now it is `debian12-arm-lts` but that doesn't make much sense, I'd say we rename it to debian11 manually because it should be compatible with that.

**Comment by julianoes** [comment]
Here to test: https://github.com/mavlink/MAVSDK/releases/download/v2.11.0/libmavsdk-dev_2.11.0_debian11_arm64-lts.deb

**Comment by AlexKlimaj** [comment]
Hm, installed the debian11 release, our logloader code builds. But then the program segfaults when trying to run it.

```jetson@jetson:~/code/logloader$ ./build/logloader
Segmentation fault (core dumped)
```

**Comment by julianoes** [comment]
Check with gdb where it segfaults. I bet it's `std::filesystem::path`.

**Pull request merged**
