### PR TITLE
[master] Fix the iterator not in same container bug when compiling with MSVC2019

### LINKED ISSUE #1357: [windows10] cannot connected to FCU
I'm using MAVSDK in windows10. Actually already used in version 0.33.1, and worked good. But these days, update to 0.37.0 and have a trouble.

Here is my build command.

```
git clone https://github.com/mavlink/MAVSDK.git -b v0.37.0
cd MAVSDK
git submodule update --init --recursive
cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=build/install_debug -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -Bbuild/debug
cmake --build build/debug --config Debug --target install
```

And in my Qt, here is initial code.

```
  mav_sdk_ = std::make_shared<mavsdk::Mavsdk>();
  mavsdk::Mavsdk::Configuration configuration(mavsdk::Mavsdk::Configuration::UsageType::CompanionComputer);

  mav_sdk_->set_configuration(configuration);

  if (mav_sdk_->add_udp_connection(mavlink_port) == mavsdk::ConnectionResult::Success)
    mav_sdk_->subscribe_on_new_system(std::bind(&DroneControl::cbDiscoverNewSystem, this));
```

Here is my error message and debugging screenshot. Again, past version 0.33.1 works good in same code. This problem is only 0.37.0.

error1
error2

I have no idea about this. My environment is,

**MSVC2019 Community latest version
Qt Opensource 5.15.2**

P.S.
In my compile of "gimbal_protocol_v1.cpp", it occurs error. So I modified "mavsdk_gimbal.vcxproj" file in build directory,

```
<AdditionalOptions>%(AdditionalOptions) -bigobj /Wv:18</AdditionalOptions>
```

Added "/Wv:18 " option.

### PR DESCRIPTION
**Pull request by LeonVincii**
Fixed a crash when compile with MSVC2019.

Resolves #1357.

### CODE REVIEW

**Review by julianoes — APPROVED** [review]
Interesting find! Thanks a lot for the fix.

**Comment by julianoes** [comment]
@LeonVincii do you understand why the Windows build in CI fails?

**Comment by JonasVautherin** [comment]
I fixed it in ae4bec97ba5874a20b73bcf00ec46fafb1037f39, but it seems like @LeonVincii's branch [is outdated](https://github.com/LeonVincii/MAVSDK/blob/master/src/plugins/gimbal/gimbal_protocol_v1.cpp#L208) as compared to [`develop`](https://github.com/mavlink/MAVSDK/blob/develop/src/plugins/gimbal/gimbal_protocol_v1.cpp#L208).

@LeonVincii: please just rebase develop, I think that may do it :+1:

**Review by JonasVautherin — APPROVED** [review]
Happy to see that it works! Note that I added a link to the original issue in your PR description: "Resolves #1357".

Thanks @LeonVincii :blush:

**Comment by LeonVincii** [comment]
Just renamed the variable to align the naming style with the rest of the codebase.

**Comment by LeonVincii** [comment]
> @LeonVincii do you understand why the Windows build in CI fails?

I'm not sure if it's related to tests. When I was building it on my PC, I had to turn off all tests. I found that some of the tests were building debug even when I was building release, and it gave me some compiling errors.

**Comment by LeonVincii** [comment]
> I fixed it in [ae4bec9](https://github.com/mavlink/MAVSDK/commit/ae4bec97ba5874a20b73bcf00ec46fafb1037f39), but it seems like @LeonVincii's branch [is outdated](https://github.com/LeonVincii/MAVSDK/blob/master/src/plugins/gimbal/gimbal_protocol_v1.cpp#L208) as compared to [`develop`](https://github.com/mavlink/MAVSDK/blob/develop/src/plugins/gimbal/gimbal_protocol_v1.cpp#L208).
> 
> @LeonVincii: please just rebase develop, I think that may do it 👍

@JonasVautherin Thanks. I created a new PR #1363 on the develop branch. But I'd still recommend applying this change to master as well, as the master is labeled as the latest stable build on the website, many people might want to use master in the favor of being stable.

**Comment by JonasVautherin** [comment]
Closing in favor of #1363, I don't think we need this as a hotfix in master (we will make a new release soon)

**Pull request closed without merging**
