### PR TITLE
Offboard pos global

### LINKED ISSUE #939: Support for global position setpoints with SET_POSITION_TARGET_GLOBAL_INT
As mentioned in here in [#12819](https://github.com/PX4/Firmware/pull/12819), MAVSDK does not support global position setpoints yet. According to @julianoes [comments](https://github.com/PX4/Firmware/pull/12819#issuecomment-526110965),  it seems not too hard to add a block of codes on the MAVSDK side. Is there any plan to add that?

### PR DESCRIPTION
**Pull request by romain-chiap**
Offboard global position control using [SET_POSITION_TARGET_GLOBAL_INT](https://mavlink.io/en/messages/common.html#SET_POSITION_TARGET_GLOBAL_INT), (latitude, longitude, altitude relative from home, and yaw).

Tested successfully in [sih](https://docs.px4.io/v1.12/en/simulation/simulation-in-hardware.html) simulator with a quad and a fw.

Proto is in [PR-264](https://github.com/mavlink/MAVSDK-Proto/pull/264)

Resolves #939

### CODE REVIEW

**Comment by romain-chiap** [comment]
I'd like to use the same proto for MAV_FRAME_GLOBAL_RELATIVE_ALT_INT and MAV_FRAME_GLOBAL_INT. Just by creating another function send_position_global_amsl().
Is it going against the philosophy of MAVSDK? Shall I rather create another proto?

BTW I don't understand anything of what's happening in offboard_service_impl_test.cpp. I just copied-past what was done for position_ned_yaw, to make the compiler happy 😛

**Comment by JonasVautherin** [comment]
> Just by creating another function send_position_global_amsl().
> Is it going against the philosophy of MAVSDK? Shall I rather create another proto?

Not sure what you mean exactly. You added your `set_position_global` function with:

```
rpc SetPositionGlobal(SetPositionGlobalRequest) returns(SetPositionGlobalResponse) { option (mavsdk.options.async_type) = SYNC; }
```

To generate `set_position_global_amsl`, you will need to add a definition in the proto file (together with the `SetPositionGlobalAmslRequest`/`SetPositionGlobalAmslResponse`) as well, otherwise they won't get generated.

However, you can reuse the `message PositionGlobalYaw`, and you can do whatever you want in the implementation (in `offboard_impl.cpp`), as long as it implements the functions generated from the proto. So if `set_position_global_amsl` is very similar to `set_position_global`, you can have a shared private function in `offboard_impl.cpp` that is used by both.

Does that answer your question?

**Comment by JonasVautherin** [comment]
I merged https://github.com/mavlink/MAVSDK-Proto/pull/264, would you mind updating the submodule here to point to `main` on mavsdk-proto? :blush:

**Comment by romain-chiap** [comment]
submodule updated!

**Pull request merged**
