### PR TITLE
Added Manual Control Module in Service

### PR DESCRIPTION
**Pull request by hrnbot**
Resolves https://github.com/mavlink/MAVSDK-Python/issues/243

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Thanks for the contribution! Does it build and work for you? The CI here fails on

```In file included from /home/runner/work/MAVSDK/MAVSDK/src/backend/src/backend.cpp:7:0:
/home/runner/work/MAVSDK/MAVSDK/src/backend/src/grpc_server.h:27:10: fatal error: plugins/manual_control/manual_control.h: No such file or directory
 #include "plugins/manual_control/manual_control.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~```

**Comment by JonasVautherin** [comment]
Using dockcross you can have a look at what we do in CI: https://github.com/mavlink/MAVSDK/blob/develop/.github/workflows/main.yml#L228-L233

Where you want to replace `${{ matrix.arch_name }}` with linux-arm64.

This said, your PR seems to fail on every platform. On what platform did you test it?

**Review by julianoes — APPROVED** [review]

**Comment by julianoes** [comment]
Something is odd:

```
 [ 74%] Building CXX object src/integration_tests/CMakeFiles/integration_tests_runner.dir/action_hover_sync.cpp.o
In file included from /work/src/backend/src/backend.cpp:7:
/work/src/backend/src/grpc_server.h:27:10: fatal error: plugins/manual_control/manual_control.h: No such file or directory
 #include "plugins/manual_control/manual_control.h"
```

**Comment by julianoes** [comment]
@hrnbot I've added a commit, let's see if this makes CI happier.

**Comment by julianoes** [comment]
>  Err:1 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 libcurl4-openssl-dev amd64 7.58.0-2ubuntu3.9
  404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.58.0-2ubuntu3.9_amd64.deb  404  Not Found [IP: 52.177.174.250 80]

This one looks like a CI issue unrelated.

```
[ 61%] Building CXX object src/plugins/ftp/CMakeFiles/mavsdk_ftp.dir/ftp_impl.cpp.o
/work/src/plugins/ftp/ftp_impl.cpp: In member function 'void mavsdk::FtpImpl::download_async(const string&, const string&, mavsdk::Ftp::DownloadCallback)':
/work/src/plugins/ftp/ftp_impl.cpp:318:90: error: use of deleted function 'std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)'
         std::ofstream(local_path, std::fstream::trunc | std::fstream::binary), local_path});
```

And this one is also unrelated, I think.

**Comment by julianoes** [comment]
I'm merging it and then checking CI again.

**Pull request merged**
