### PR TITLE
Update gimbal_full_control.cpp example

### PR DESCRIPTION
**Pull request by KarthiAru**
- Added `gimbal_id` parameter to all gimbal related methods.
- Replaced the non-existing `set_mode` method with the `set_angles` method.
- Revised `set_angle` methods to include the correct parameters

### CODE REVIEW

**Review by julianoes — DISMISSED** [review]
Oh, that's great, thanks!

**Review by JonasVautherin — APPROVED** [review]
Thanks!

The style check is failing, though 😕

**Comment by JonasVautherin** [comment]
I think you have to run `./tools/fix_style.sh` from Ubuntu 24.04. It used to work with a container if you are not on Ubuntu 24. Maybe `./tools/tools/run-docker-clang-format.sh ./tools/fix_style.sh`? I haven't used it in a while 🙈

**Comment by KarthiAru** [comment]
@JonasVautherin Thanks. I've fixed the style on Ubuntu 24.04

**Review by JonasVautherin — APPROVED** [review]

**Pull request merged**
