### PR TITLE
Action plugin 'set_actuator_async' switch statement index changed to zero-based

### PR DESCRIPTION
**Pull request by elbarto1980**
The pull request is related to this [issue](https://github.com/mavlink/MAVSDK/issues/2102)

### CODE REVIEW

**Review by julianoes — APPROVED** [review]
Thanks!

Should we return an error with something like invalid argument if someone supplies an index of 0?

**Comment by elbarto1980** [comment]
Actually I thought about returning an error at first, but then I saw that neither the original method did any check on the parameters range (index is a const int). So I kept it that way.

I don't have full knowledge of how errors are handled in the async commands but, looking at the source code of other methods of the same class (e.g. `goto_location_async`), I presume that, in the else branch, I should use the method:
`command_result_callback(Action::Result::CommandDenied, callback);`
and then return 

Is it right?

**Comment by julianoes** [comment]
Yes, but `CommandDenied` is only for the case where the vehicle denies it, and it looks like we don't have an `InvalidArgument` for action. Let's merge it like this and add that later.

Thanks again.

**Comment by elbarto1980** [comment]
I’m happy to help. Thank you!

**Pull request merged**
