### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by julianoes**
Not sure why CI didn't highlight these warnings @bkueng.

### CODE REVIEW

**Comment by bkueng** [comment]
CI is using `WERROR=OFF` from what I see.

**Comment by julianoes** [comment]
Oh, you're right. That shouldn't be that way...

**Comment by julianoes** [comment]
Haha, for now: https://github.com/mavlink/MAVSDK/commit/d3b3c500e7784552f82065f4930863d15eb109ec

**Comment by julianoes** [comment]
FYI: locally this builds for me with latest MSVC 19.39.

So, hopefully with https://github.com/actions/runner-images/issues/9701 this will pass again.

**Comment by julianoes** [comment]
Closing in favor of #2297.

**Pull request closed without merging**
