### PR TITLE
More camera server functionality

### PR DESCRIPTION
**Pull request by tbago**
1. add start and stop video function, add sample code for start stop video.
2. add start and stop video streaming function, add stream id int camera side (the camera can support multi video streaming).
3. storage functions
4. capture status
5. param changed subscriptions

### CODE REVIEW

**Review by julianoes — COMMENTED** [review]
This will need the proto submodule updated once it has been merged. Otherwise, I think this looks good.

**Comment by tbago** [comment]
Ok I will update the proto submodule, but not for now. I have more function need commit.

**Comment by tbago** [comment]
Add basic camera function complete.

When the proto repo is accept, will update the submodule, and complete this PR.

Other camera function will implement in new PR later.

**Comment by julianoes** [comment]
Thanks @tbago, let me review the proto PR again.

**Comment by tbago** [comment]
@julianoes Yeah, you don't need review this PR until the [Mavsdk-Proto](https://github.com/mavlink/MAVSDK-Proto/pull/320) is ready.

For now may need to add more unit tests for camera server.

**Review by JonasVautherin — APPROVED** [review]

**Pull request merged**
